(
        "Tiene que llover",
        "Karl Ove Knausgard",
        "De los años que captura este libro, apenas quedan unos pocos recuerdos, nos dice el autor. Y, por encima de todos, uno: el de la ignorancia, la ingenuidad, el fracaso. Y, sin embargo, en Tiene que llover un Knausgård concentrado y frontal exprime su prodigiosa capacidad evocativa para, cerrando el círculo, describir el camino por el que llegó a convertirse en el autor que conocimos con La muerte del padre, y dar vívido testimonio de los impedimentos, errores y tropiezos que contribuyeron a conformarlo.\n\nUn camino que empieza, en 1988, donde terminaría catorce años más tarde: en Bergen, con un veinteañero Karl Ove convertido en el alumno más joven de la Academia de Escritura de la ciudad, y pletórico de un entusiasmo que no tarda en abandonarle. Y es que el precoz novelista se revela inepto en todos los frentes: el social, el amoroso, el literario. Sus textos son infantiles, están hechos de clichés, y Karl Ove combate (bebiendo, saliendo de esta, enzarzándose en peleas o coqueteando con la delincuencia) la lacerante constatación de no ser un escritor en absoluto.\n\nPese a ello, persiste: va a la universidad, envía algunos cuentos, cosecha algunos rechazos; descubre un talento inesperado para la crítica literaria. Y tras sus primeros romances frustrados, el amor: Tonje, con la que se casará, y junto a la que verá cómo, cuando ya casi no lo esperaba, se convierte en algo parecido al autor que siempre había anhelado ser. Hasta que la insatisfacción que también lo había perseguido siempre se imponga, dando un sonoro carpetazo a la época que se dibuja en este libro: un tiempo del que emerge completa la silueta de un hombre atormentado, contradictorio e imperfecto, cada vez más próximo a emprender el autoanálisis inmisericorde que le llevará a descubrir el alcance de su vocación, tan trabajosamente conquistada. El mismo autoanálisis al que los lectores de todo el mundo han asistido, imantados, a lo largo de una saga de ambición infrecuente y escala titánica, que con Tiene que llover (veloz, libre, esencial, desnudo) entrega otro volumen inolvidable muy cerca de la culminación definitiva.",
        "Anagrama",
        "9788433979834",
        "https://www.anagrama-ed.es/uploads/media/portadas/0001/17/xthumb_16343_portadas_big.jpeg.pagespeed.ic.Cgwghitvxx.webp"
    ), (
        "Invierno",
        "Rick Bass",
        "En el valle del Yaak, en Montana, viven apenas treinta personas y un número indeterminado de osos, lobos, coyotes, pumas, alces… Un lugar sin duda salvaje y remoto. De hecho, allí la mayoría de las casas carecen de electricidad o teléfono. Para sus habitantes, sin embargo, eso no parece ser un problema. Son leñadores, tramperos, guías de caza, domadores de caballos, tejedores de atrapasueños, veteranos de Vietnam, un payaso de rodeos jubilado… También hay un par de fugitivos, aunque quizás, de un modo u otro, todos lo sean: todos han llegado hasta allí huyendo de algo y aquel aislamiento los hace sentir seguros.\n\nDesde el primer instante, Rick Bass y su mujer se ven irremediablemente atraídos por aquella realidad indómita. Y deciden rendirse a su silencio y a su misterio, encarnados en la lenta e imperturbable caída de la nieve, que parece ralentizar el tiempo y ofrecer perdón para todas las culpas. Alquilan una casa, conocen a los excéntricos habitantes del valle, se emborrachan en el Dirty Shame y empiezan a prepararse para el invierno: algo que en su Texas natal nunca han vivido, menos aún a treinta grados bajo cero y sin más tecnología que una lámpara de aceite, una motosierra y una chimenea. Él comienza a escribir, a relatar su cita y su encuentro con el invierno, con ese paisaje blanco, ingobernable y feroz que reclama de manera incansable vidas para seguir avanzando. Pronto recuerda aquella vieja historia que contaba un aventurero a las gentes de la ciudad: en Yellowstone el frío era tal que a los tramperos las palabras se les congelaban según salían de sus bocas, y debían recogerlas, guardarlas cuidadosamente y colocarlas ante el fuego por la noche, para ensartarlas en frases y saber lo que se habían dicho durante el día. Eso hace también Rick Bass.\n\nAhora que nuestro invierno es cada vez menos invierno, que su belleza es cada vez más frágil y esquiva, este libro se presenta como un canto poderoso al níveo secreto del Gran Frío.",
        "Errata Naturae",
        "9788416544837",
        "https://erratanaturae.com/nouveau/wp-content/uploads/2020/04/portada_invierno_3ed-web-1-500x771.jpg"
    ), (
        "Canciones de amor a quemarropa",
        "Nickolas Butler",
        "Henry, Lee, Kip y Ronny crecieron juntos en el mismo pueblo de Wisconsin, Little Wing. Amigos desde niños, sus vidas comenzaron de manera similar, pero han tomado caminos distintos. Henry se quedó en el pueblo y se casó con su primera novia, mientras que el resto lo abandonó en busca de algo más: Ronny se convirtió en un famoso cowboy de rodeo, Kip en exitoso agente de bolsa y Lee en una estrella de rock de fama mundial.\n\nCuando se vuelven a reunir en una boda, todos tratan de recuperar su vieja amistad pese a lo mucho que han cambiado. Entre la alegría del encuentro las antiguas rivalidades renacen y los viejos secretos amenazan con destrozar amistad y amor.\n\nUn relato maravilloso, emotivo y profundo que trata de un viejo tema: ¿podemos sentirnos alguna vez realmente en casa? Una novela sobre las cosas que importan: el amor y la lealtad, el poder de la música y la belleza de la naturaleza. Publicada recientemente en EE. UU., Canciones de amor a quemarropa se ha convertido en una de las sensaciones literarias del año.",
        "Libros del asteroide",
        "9788415625995",
        "https://www.librosdelasteroide.com/local/cache-vignettes/L210xH323/arton1234-185ad.jpg"
    ), (
        "Un paseo invernal",
        "Henry David Thoreau",
        "Reunimos en este libro dos de los textos más bellos y menos conocidos del autor de Walden: «Un paseo invernal» relata una caminata inolvidable por el corazón de los Grandes Fríos hacia la primavera de la existencia; «Caminar» es un ensayo magistral sobre el arte del paseo y una defensa cerrada de la vida salvaje y libre, tanto de los animales como de los seres humanos.\n\n«En la profundidad del bosque, completamente solos, mientras el viento sacude la nieve de los árboles y dejamos atrás los últimos rastros humanos, nuestras reflexiones adquieren una riqueza y variedad muy superiores a las que ostentan cuando estamos inmersos en la vida de las ciudades. El zorzal y el trepador son una compañía más estimulante que la de políticos y filósofos, a los que volveremos a ver como quien se reencuentra con unos viejos y vulgares compañeros. En este valle solitario, en el que un riachuelo desagua las laderas cubiertas de hielo estriado y cristales de infinitos matices, entre los que sobresalen los juncos y la avena salvaje, y se elevan los abetos y las tsugas, nuestra vida es más serena y verdaderamente digna de contemplación».",
        "Errata Naturae",
        "9788415217831",
        "https://erratanaturae.com/nouveau/wp-content/uploads/2020/05/Portada_Unpaseoinvernal.jpg"
    ), (
        "Walden",
        "Henry David Thoreau",
        "En 1845 Thoreau abandona la casa familiar de Concord y se instala en la cabaña que ha construido junto a la laguna de Walden. Pero no se marcha a los bosques para «jugar a la vida», sino para «vivirla intensamente de principio a fin». A partir de esa experiencia escribe uno de los clásicos fundamentales del ensayo moderno. Walden es tanto un experimento literario sin precedentes como un manual para la buena vida: un libro escrito contra toda servidumbre y a favor de la felicidad como única riqueza del ser humano. Walden es una defensa de la vida libre y salvaje, así como una crítica feroz de la sociedad y sus imposiciones, que apenas han variado desde aquella fecha. Walden es un cuestionamiento radical y directo de la institución del trabajo como adocenamiento y del mercado como único dios, así como una lúcida defensa de la simplificación de la vida y del camino que nos lleva a perseguir su esencia y sus placeres cotidianos. Walden es una reflexión sobre la necesidad de preservar tanto la naturaleza y el planeta como el meollo de nuestra propia existencia individual e irreductible. Walden habla de lagunas salvajes y hombres sabios, alces y shakespeares, esclavos huidos y trabajadores sonámbulos, las montañas de Nueva Inglaterra y el Bhagavad Gita, la belleza del fuego hogareño y la Gran Nevada, el silbido devastador del ferrocarril y el recóndito ulular del búho, la erudición de los indios Massasoit y la banalidad de los eruditos de Harvard, la belleza absoluta de la soledad y la importancia inconmensurable de la amistad, el bienestar que exhiben las marmotas y el malestar que aqueja a la mayoría de los seres humanos. Según el propio Thoreau, «Walden es un libro escrito para esa mayoría de hombres que está descontenta con su vida y con los tiempos que le ha tocado vivir, pero que podría mejorarlos. Y también para aquéllos en apariencia ricos, pero que en realidad han acumulado cosas inútiles y no saben muy bien qué hacer con ellas».",
        "Errata Naturae",
        "9788415217459",
        "https://erratanaturae.com/nouveau/wp-content/uploads/2020/05/Portada-Walden.jpg"
    ), (
        "Life is good if you don't weaken",
        "Seth",
        "Seth emprende aquí un viaje en busca de sí mismo y del sentido de la vida a través de la obra de Kalo, un historietista olvidado de los años cuarenta y cincuenta a quien descubrió por casualidad en un número antiguo de The New Yorker y cuyo trabajo lo obsesiona y le fascina.\n\nUna tarea compulsiva que lo lleva a sumergirse en horas de lectura e investigación, y a repasar pilas de libros y revistas viejos con la esperanza de encontrar algún fragmento del pasado al que poder aferrarse en última instancia. Una aventura, en definitiva, que nos transporta con fuerza y pasión en la distancia y en el tiempo.\n\nLa vida es buena si no te rindes, una obra excepcional que demuestra la fuerza del cómic como forma narrativa, es la primera novela gráfica de Seth. El libro apareció por primera vez, de modo serializado, entre 1993 y 1996 en la saga autobiográfica Palookaville. La versión definitiva, en un solo volumen, situó a Seth en el panorama del cómic mundial.",
        "Salamandra Graphic",
        "9788416131860",
        "https://m.media-amazon.com/images/I/51+2sXapm0L.jpg"
    ), (
        "Fragmentos",
        "George Steiner",
        "George Steiner desarrolla una síntesis de sus intereses intelectuales y vitales y reflexiona sobre la educación, el mal, el dinero o la religión.\n\nEl hallazgo ficticio de un pergamino dañado por el fuego en las ruinas de una villa de Herculano invita a George Steiner a interpretar el sentido del texto original, que algunos atribuyen a Epicarno de Agra. El legado de este supuesto moralista y retórico del siglo II a. C. se confunde con lo que podría ser una síntesis de los intereses intelectuales y vitales del propio Steiner.\n\nJugando con la conjetura, George Steiner reflexiona sobre la elocuencia del silencio (lo no expresado) en la poesía y la filosofía, las gratificaciones de la amistad, el potencial de la educación y la rareza del talento, la realidad ontológica del mal, la omnipotencia del dinero, los peligros de la religión, la trascendencia de la música y la libertad de elegir la muerte.",
        "Siruela",
        "9788416396689",
        "https://www.siruela.com/libros/grandes/9788416396689_L38_04_l.png"
    ), (
        "Una historia crepuscular",
        "Stefan Zweig",
        "Bob, un adolescente inglés de familia acomodada, pasa el verano en la campiña escocesa. Una noche, mientras da un paseo por el jardín, vive un breve encuentro amoroso con una enigmática joven que termina esfumándose antes de que él consiga saber quién es. Exaltado por la intensidad de unos sentimientos desconocidos e inimaginables hasta entonces, se propone desvelar la identidad de la muchacha. Un relato íntimo y evocador que narra el periplo hacia la madurez de un joven que, en el ocaso de su infancia, descubre las emociones y la complejidad del amor adulto.",
        "El acantilado",
        "9788416011681",
        "https://www.acantilado.es/wp-content/uploads/una-historia-crepuscular-416x650.jpg"
    ), (
        "Petit pays",
        "Gael Faye",
        "En 1992, Gabriel, dix ans, vit au Burundi avec son père français, entrepreneur, sa mère rwandaise et sa petite sœur, Ana, dans un confortable quartier d’expatriés. Gabriel passe le plus clair de son temps avec ses copains, une joyeuse bande occupée à faire les quatre cents coups. Un quotidien paisible, une enfance douce qui vont se disloquer en même temps que ce « petit pays » d’Afrique brutalement malmené par l’Histoire. Gabriel   voit avec inquiétude ses parents se séparer, puis la guerre civile se profiler, suivie du drame rwandais. Le quartier est bouleversé. Par vagues successives, la violence l’envahit, l’imprègne, et tout bascule. Gabriel se croyait un enfant, il va se découvrir métis, Tutsi, Français…\n« J’ai écrit ce roman pour crier à l’univers que nous avons existé, avec nos vies simples, notre train-train, notre ennui, que nous avions des bonheurs qui ne cherchaient qu’à le rester avant d'être expédiés aux quatre coins du monde et de devenir une bande d’exilés, de réfugiés, d’immigrés, de migrants. »\nAvec un rare sens du romanesque, Gaël Faye évoque les tourments et les interrogations d’un enfant pris dans une Histoire qui le fait grandir plus vite que prévu. Nourri d’un drame que l’auteur connaît bien, un premier roman d’une ampleur exceptionnelle, parcouru d’ombres et de lumière, de tragique et d’humour, de personnages qui tentent de survivre à la tragédie.",
        "Grasset",
        "9782246857334",
        "https://m.media-amazon.com/images/I/41E5ivopozL.jpg"
    ), (
        "La muerte del padre",
        "Karl Ove Knausgard",
        "Karl Ove Knausgård está luchando con su tercera novela casi diez años después de que su padre se emborrachara hasta morir. Quiere que sea una obra maestra, pero le atormentan las dudas sobre su talento como escritor y se pasa los días imaginando epitafios nada halagadores para sí mismo. La mente de Karl Ove deambula entre sus frustraciones actuales y su relación con su familia y el pasado –su infancia, las inseguridades de la adolescencia, el descubrimiento del sexo, del alcohol, esa «bebida mágica», su pasión por el rock– cuando su padre tenía la misma edad que él ahora. Era un niño serio y a menudo angustiado, con un hermano más feliz y menos complicado que él, una madre apacible y cariñosa pero casi invisible, y un padre distante e imprevisible. Un padre cuya muerte prematura suscitó en él emociones contradictorias, alivio, y también un profundo dolor, sentimientos que el protagonista aún no ha conseguido aceptar.\n\nLa muerte del padre es la primera novela de las seis que conforman Mi lucha y que pueden ser leídas de forma independiente o como partes de un proyecto muy ambicioso. Karl Ove Knausgård se embarca en una exploración proustiana de su pasado y desmenuza la historia de su propia vida hasta obtener las «partículas elementales». El resultado es una historia universal de los combates –grandes y pequeños– que todos debemos librar en nuestras vidas, una novela tan profunda como absorbente que nos atrapa desde la primera página, escrita como si la propia vida de su autor estuviera en juego.",
        "Anagrama",
        "9788433978448",
        "https://www.anagrama-ed.es/uploads/media/portadas/0001/15/xthumb_14725_portadas_big.jpeg.pagespeed.ic.Ckbfd80yMk.webp"
    )